//
//  SymbolPairs.swift
//  VIPexample
//
//  Created by Danyl Timofeyev on 10.10.2021.
//

import Foundation

enum Symbols: String {
    case INCHBUSD = "1INCHBUSD"
    case INCHDOWNUSDT = "1INCHDOWNUSDT"
    case INCHUPUSDT = "1INCHUPUSDT"
    case INCHUSDT = "1INCHUSDT"
    case AAVEBKRW
    case AAVEBNB
    case AAVEBRL
    case AAVEBTC
    case AAVEBUSD
    case AAVEDOWNUSDT
    case AAVEETH
    case AAVEUPUSDT
    case AAVEUSDT
    case ACMBTC
    case ACMBUSD
    case ACMUSDT
    case ADAAUD
    case ADABIDR
    case ADABKRW
    case ADABNB
    case ADABRL
    case ADABTC
    case ADABUSD
    case ADADOWNUSDT
    case ADAETH
    case ADAEUR
    case ADAGBP
    case ADAPAX
    case ADARUB
    case ADATRY
    case ADATUSD
    case ADAUPUSDT
    case ADAUSDC
    case ADAUSDT
    case ADXBNB
    case ADXBTC
    case ADXBUSD
    case ADXETH
    case AEBNB
    case AEBTC
    case AEETH
    case AERGOBTC
    case AERGOBUSD
    case AGIBNB
    case AGIBTC
    case AGIETH
    case AGIXBTC
    case AGLDBNB
    case AGLDBTC
    case AGLDBUSD
    case AGLDUSDT
    case AIONBNB
    case AIONBTC
    case AIONBUSD
    case AIONETH
    case AIONUSDT
    case AKROBTC
    case AKROUSDT
    case ALGOBIDR
    case ALGOBNB
    case ALGOBTC
    case ALGOBUSD
    case ALGOPAX
    case ALGOTUSD
    case ALGOUSDC
    case ALGOUSDT
    case ALICEBIDR
    case ALICEBTC
    case ALICEBUSD
    case ALICEUSDT
    case ALPACABNB
    case ALPACABTC
    case ALPACABUSD
    case ALPACAUSDT
    case ALPHABNB
    case ALPHABTC
    case ALPHABUSD
    case ALPHAUSDT
    case AMBBNB
    case AMBBTC
    case AMBETH
    case ANKRBNB
    case ANKRBTC
    case ANKRPAX
    case ANKRTUSD
    case ANKRUSDC
    case ANKRUSDT
    case ANTBNB
    case ANTBTC
    case ANTBUSD
    case ANTUSDT
    case APPCBNB
    case APPCBTC
    case APPCETH
    case ARBNB
    case ARBTC
    case ARBUSD
    case ARDRBNB
    case ARDRBTC
    case ARDRETH
    case ARDRUSDT
    case ARKBTC
    case ARKETH
    case ARNBTC
    case ARNETH
    case ARPABNB
    case ARPABTC
    case ARPABUSD
    case ARPARUB
    case ARPATRY
    case ARPAUSDT
    case ARUSDT
    case ASRBTC
    case ASRUSDT
    case ASTBTC
    case ASTETH
    case ATABNB
    case ATABTC
    case ATABUSD
    case ATAUSDT
    case ATMBTC
    case ATMBUSD
    case ATMUSDT
    case ATOMBNB
    case ATOMBTC
    case ATOMBUSD
    case ATOMPAX
    case ATOMTUSD
    case ATOMUSDC
    case ATOMUSDT
    case AUCTIONBTC
    case AUCTIONBUSD
    case AUDBUSD
    case AUDIOBTC
    case AUDIOBUSD
    case AUDIOUSDT
    case AUDUSDT
    case AUTOBTC
    case AUTOBUSD
    case AUTOUSDT
    case AVABNB
    case AVABTC
    case AVABUSD
    case AVAUSDT
    case AVAXBIDR
    case AVAXBNB
    case AVAXBTC
    case AVAXBUSD
    case AVAXEUR
    case AVAXTRY
    case AVAXUSDT
    case AXSAUD
    case AXSBIDR
    case AXSBNB
    case AXSBRL
    case AXSBTC
    case AXSBUSD
    case AXSUSDT
    case BADGERBTC
    case BADGERBUSD
    case BADGERUSDT
    case BAKEBNB
    case BAKEBTC
    case BAKEBUSD
    case BAKEUSDT
    case BALBNB
    case BALBTC
    case BALBUSD
    case BALUSDT
    case BANDBNB
    case BANDBTC
    case BANDBUSD
    case BANDUSDT
    case BARBTC
    case BARBUSD
    case BARUSDT
    case BATBNB
    case BATBTC
    case BATBUSD
    case BATETH
    case BATPAX
    case BATTUSD
    case BATUSDC
    case BATUSDT
    case BCCBNB
    case BCCBTC
    case BCCETH
    case BCCUSDT
    case BCDBTC
    case BCDETH
    case BCHABCBTC
    case BCHABCBUSD
    case BCHABCPAX
    case BCHABCTUSD
    case BCHABCUSDC
    case BCHABCUSDT
    case BCHABUSD
    case BCHBNB
    case BCHBTC
    case BCHBUSD
    case BCHDOWNUSDT
    case BCHEUR
    case BCHPAX
    case BCHSVBTC
    case BCHSVPAX
    case BCHSVTUSD
    case BCHSVUSDC
    case BCHSVUSDT
    case BCHTUSD
    case BCHUPUSDT
    case BCHUSDC
    case BCHUSDT
    case BCNBNB
    case BCNBTC
    case BCNETH
    case BCPTBNB
    case BCPTBTC
    case BCPTETH
    case BCPTPAX
    case BCPTTUSD
    case BCPTUSDC
    case BEAMBNB
    case BEAMBTC
    case BEAMUSDT
    case BEARBUSD
    case BEARUSDT
    case BELBNB
    case BELBTC
    case BELBUSD
    case BELUSDT
    case BETABNB
    case BETABTC
    case BETABUSD
    case BETAUSDT
    case BETHETH
    case BGBPUSDC
    case BIFIBNB
    case BIFIBUSD
    case BKRWBUSD
    case BKRWUSDT
    case BLZBNB
    case BLZBTC
    case BLZBUSD
    case BLZETH
    case BLZUSDT
    case BNBAUD
    case BNBBEARBUSD
    case BNBBEARUSDT
    case BNBBIDR
    case BNBBKRW
    case BNBBRL
    case BNBBTC
    case BNBBULLBUSD
    case BNBBULLUSDT
    case BNBBUSD
    case BNBDAI
    case BNBDOWNUSDT
    case BNBETH
    case BNBEUR
    case BNBGBP
    case BNBIDRT
    case BNBNGN
    case BNBPAX
    case BNBRUB
    case BNBTRY
    case BNBTUSD
    case BNBUAH
    case BNBUPUSDT
    case BNBUSDC
    case BNBUSDP
    case BNBUSDS
    case BNBUSDT
    case BNBZAR
    case BNTBTC
    case BNTBUSD
    case BNTETH
    case BNTUSDT
    case BONDBNB
    case BONDBTC
    case BONDBUSD
    case BONDUSDT
    case BOTBTC
    case BOTBUSD
    case BQXBTC
    case BQXETH
    case BRDBNB
    case BRDBTC
    case BRDETH
    case BTCAUD
    case BTCBBTC
    case BTCBIDR
    case BTCBKRW
    case BTCBRL
    case BTCBUSD
    case BTCDAI
    case BTCDOWNUSDT
    case BTCEUR
    case BTCGBP
    case BTCGYEN
    case BTCIDRT
    case BTCNGN
    case BTCPAX
    case BTCRUB
    case BTCSTBTC
    case BTCSTBUSD
    case BTCSTUSDT
    case BTCTRY
    case BTCTUSD
    case BTCUAH
    case BTCUPUSDT
    case BTCUSDC
    case BTCUSDP
    case BTCUSDS
    case BTCUSDT
    case BTCVAI
    case BTCZAR
    case BTGBTC
    case BTGBUSD
    case BTGETH
    case BTGUSDT
    case BTSBNB
    case BTSBTC
    case BTSBUSD
    case BTSETH
    case BTSUSDT
    case BTTBNB
    case BTTBRL
    case BTTBTC
    case BTTBUSD
    case BTTEUR
    case BTTPAX
    case BTTTRX
    case BTTTRY
    case BTTTUSD
    case BTTUSDC
    case BTTUSDT
    case BULLBUSD
    case BULLUSDT
    case BURGERBNB
    case BURGERBUSD
    case BURGERUSDT
    case BUSDBIDR
    case BUSDBKRW
    case BUSDBRL
    case BUSDBVND
    case BUSDDAI
    case BUSDIDRT
    case BUSDNGN
    case BUSDRUB
    case BUSDTRY
    case BUSDUAH
    case BUSDUSDT
    case BUSDVAI
    case BUSDZAR
    case BZRXBNB
    case BZRXBTC
    case BZRXBUSD
    case BZRXUSDT
    case C98BNB
    case C98BRL
    case C98BTC
    case C98BUSD
    case C98USDT
    case CAKEAUD
    case CAKEBNB
    case CAKEBRL
    case CAKEBTC
    case CAKEBUSD
    case CAKEGBP
    case CAKEUSDT
    case CDTBTC
    case CDTETH
    case CELOBTC
    case CELOUSDT
    case CELRBNB
    case CELRBTC
    case CELRBUSD
    case CELRUSDT
    case CFXBTC
    case CFXBUSD
    case CFXUSDT
    case CHATBTC
    case CHATETH
    case CHRBNB
    case CHRBTC
    case CHRBUSD
    case CHRUSDT
    case CHZBNB
    case CHZBRL
    case CHZBTC
    case CHZBUSD
    case CHZEUR
    case CHZGBP
    case CHZTRY
    case CHZUSDT
    case CKBBTC
    case CKBBUSD
    case CKBUSDT
    case CLOAKBTC
    case CLOAKETH
    case CLVBNB
    case CLVBTC
    case CLVBUSD
    case CLVUSDT
    case CMTBNB
    case CMTBTC
    case CMTETH
    case CNDBNB
    case CNDBTC
    case CNDETH
    case COCOSBNB
    case COCOSBTC
    case COCOSUSDT
    case COMPBNB
    case COMPBTC
    case COMPBUSD
    case COMPUSDT
    case COSBNB
    case COSBTC
    case COSUSDT
    case COTIBNB
    case COTIBTC
    case COTIBUSD
    case COTIUSDT
    case COVERBUSD
    case COVERETH
    case CREAMBNB
    case CREAMBUSD
    case CRVBNB
    case CRVBTC
    case CRVBUSD
    case CRVUSDT
    case CTKBNB
    case CTKBTC
    case CTKBUSD
    case CTKUSDT
    case CTSIBNB
    case CTSIBTC
    case CTSIBUSD
    case CTSIUSDT
    case CTXCBNB
    case CTXCBTC
    case CTXCUSDT
    case CVCBNB
    case CVCBTC
    case CVCETH
    case CVCUSDT
    case CVPBUSD
    case CVPETH
    case CVPUSDT
    case DAIBNB
    case DAIBTC
    case DAIBUSD
    case DAIUSDT
    case DASHBNB
    case DASHBTC
    case DASHBUSD
    case DASHETH
    case DASHUSDT
    case DATABTC
    case DATABUSD
    case DATAETH
    case DATAUSDT
    case DCRBNB
    case DCRBTC
    case DCRBUSD
    case DCRUSDT
    case DEGOBTC
    case DEGOBUSD
    case DEGOUSDT
    case DENTBTC
    case DENTBUSD
    case DENTETH
    case DENTUSDT
    case DEXEBUSD
    case DEXEETH
    case DEXEUSDT
    case DFBUSD
    case DFETH
    case DFUSDT
    case DGBBNB
    case DGBBTC
    case DGBBUSD
    case DGBUSDT
    case DGDBTC
    case DGDETH
    case DIABNB
    case DIABTC
    case DIABUSD
    case DIAUSDT
    case DLTBNB
    case DLTBTC
    case DLTETH
    case DNTBTC
    case DNTBUSD
    case DNTETH
    case DNTUSDT
    case DOCKBTC
    case DOCKBUSD
    case DOCKETH
    case DOCKUSDT
    case DODOBTC
    case DODOBUSD
    case DODOUSDT
    case DOGEAUD
    case DOGEBIDR
    case DOGEBNB
    case DOGEBRL
    case DOGEBTC
    case DOGEBUSD
    case DOGEEUR
    case DOGEGBP
    case DOGEPAX
    case DOGERUB
    case DOGETRY
    case DOGEUSDC
    case DOGEUSDT
    case DOTAUD
    case DOTBIDR
    case DOTBKRW
    case DOTBNB
    case DOTBRL
    case DOTBTC
    case DOTBUSD
    case DOTDOWNUSDT
    case DOTEUR
    case DOTGBP
    case DOTNGN
    case DOTRUB
    case DOTTRY
    case DOTUPUSDT
    case DOTUSDT
    case DREPBNB
    case DREPBTC
    case DREPUSDT
    case DUSKBNB
    case DUSKBTC
    case DUSKPAX
    case DUSKUSDC
    case DUSKUSDT
    case DYDXBNB
    case DYDXBTC
    case DYDXBUSD
    case DYDXUSDT
    case EASYBTC
    case EASYETH
    case EDOBTC
    case EDOETH
    case EGLDBNB
    case EGLDBTC
    case EGLDBUSD
    case EGLDEUR
    case EGLDUSDT
    case ELFBTC
    case ELFBUSD
    case ELFETH
    case ELFUSDT
    case ENGBTC
    case ENGETH
    case ENJBNB
    case ENJBRL
    case ENJBTC
    case ENJBUSD
    case ENJETH
    case ENJEUR
    case ENJGBP
    case ENJUSDT
    case EOSAUD
    case EOSBEARBUSD
    case EOSBEARUSDT
    case EOSBNB
    case EOSBTC
    case EOSBULLBUSD
    case EOSBULLUSDT
    case EOSBUSD
    case EOSDOWNUSDT
    case EOSETH
    case EOSEUR
    case EOSPAX
    case EOSTRY
    case EOSTUSD
    case EOSUPUSDT
    case EOSUSDC
    case EOSUSDT
    case EPSBTC
    case EPSBUSD
    case EPSUSDT
    case ERDBNB
    case ERDBTC
    case ERDBUSD
    case ERDPAX
    case ERDUSDC
    case ERDUSDT
    case ERNBNB
    case ERNBUSD
    case ERNUSDT
    case ETCBNB
    case ETCBRL
    case ETCBTC
    case ETCBUSD
    case ETCETH
    case ETCEUR
    case ETCGBP
    case ETCPAX
    case ETCTUSD
    case ETCUSDC
    case ETCUSDT
    case ETHAUD
    case ETHBEARBUSD
    case ETHBEARUSDT
    case ETHBIDR
    case ETHBKRW
    case ETHBRL
    case ETHBTC
    case ETHBULLBUSD
    case ETHBULLUSDT
    case ETHBUSD
    case ETHDAI
    case ETHDOWNUSDT
    case ETHEUR
    case ETHGBP
    case ETHNGN
    case ETHPAX
    case ETHRUB
    case ETHTRY
    case ETHTUSD
    case ETHUAH
    case ETHUPUSDT
    case ETHUSDC
    case ETHUSDP
    case ETHUSDT
    case ETHZAR
    case EURBUSD
    case EURUSDT
    case EVXBTC
    case EVXETH
    case EZBTC
    case EZETH
    case FARMBNB
    case FARMBTC
    case FARMBUSD
    case FARMUSDT
    case FETBNB
    case FETBTC
    case FETBUSD
    case FETUSDT
    case FIDABNB
    case FIDABTC
    case FIDABUSD
    case FIDAUSDT
    case FILBNB
    case FILBTC
    case FILBUSD
    case FILDOWNUSDT
    case FILUPUSDT
    case FILUSDT
    case FIOBNB
    case FIOBTC
    case FIOBUSD
    case FIOUSDT
    case FIROBTC
    case FIROETH
    case FIROUSDT
    case FISBRL
    case FISBTC
    case FISBUSD
    case FISUSDT
    case FLMBNB
    case FLMBTC
    case FLMBUSD
    case FLMUSDT
    case FLOWBNB
    case FLOWBTC
    case FLOWBUSD
    case FLOWUSDT
    case FORBTC
    case FORBUSD
    case FORTHBTC
    case FORTHBUSD
    case FORTHUSDT
    case FORUSDT
    case FRONTBTC
    case FRONTBUSD
    case FRONTETH
    case FRONTUSDT
    case FTMBIDR
    case FTMBNB
    case FTMBTC
    case FTMBUSD
    case FTMPAX
    case FTMTUSD
    case FTMUSDC
    case FTMUSDT
    case FTTBNB
    case FTTBTC
    case FTTBUSD
    case FTTUSDT
    case FUELBTC
    case FUELETH
    case FUNBTC
    case FUNETH
    case FUNUSDT
    case FXSBTC
    case FXSBUSD
    case GALABNB
    case GALABTC
    case GALABUSD
    case GALAUSDT
    case GASBTC
    case GBPBUSD
    case GBPUSDT
    case GHSTBUSD
    case GHSTETH
    case GHSTUSDT
    case GLMBTC
    case GLMETH
    case GNOBNB
    case GNOBTC
    case GNOBUSD
    case GNOUSDT
    case GNTBNB
    case GNTBTC
    case GNTETH
    case GOBNB
    case GOBTC
    case GRSBTC
    case GRSETH
    case GRTBTC
    case GRTBUSD
    case GRTETH
    case GRTEUR
    case GRTTRY
    case GRTUSDT
    case GTCBNB
    case GTCBTC
    case GTCBUSD
    case GTCUSDT
    case GTOBNB
    case GTOBTC
    case GTOETH
    case GTOPAX
    case GTOTUSD
    case GTOUSDC
    case GTOUSDT
    case GVTBTC
    case GVTETH
    case GXSBTC
    case GXSETH
    case GXSUSDT
    case HARDBNB
    case HARDBTC
    case HARDBUSD
    case HARDUSDT
    case HBARBNB
    case HBARBTC
    case HBARBUSD
    case HBARUSDT
    case HCBTC
    case HCETH
    case HCUSDT
    case HEGICBUSD
    case HEGICETH
    case HIVEBNB
    case HIVEBTC
    case HIVEBUSD
    case HIVEUSDT
    case HNTBTC
    case HNTBUSD
    case HNTUSDT
    case HOTBNB
    case HOTBRL
    case HOTBTC
    case HOTBUSD
    case HOTETH
    case HOTEUR
    case HOTTRY
    case HOTUSDT
    case HSRBTC
    case HSRETH
    case ICNBTC
    case ICNETH
    case ICPBNB
    case ICPBTC
    case ICPBUSD
    case ICPEUR
    case ICPRUB
    case ICPUSDT
    case ICXBNB
    case ICXBTC
    case ICXBUSD
    case ICXETH
    case ICXUSDT
    case IDEXBTC
    case IDEXBUSD
    case IDEXUSDT
    case ILVBNB
    case ILVBTC
    case ILVBUSD
    case ILVUSDT
    case INJBNB
    case INJBTC
    case INJBUSD
    case INJUSDT
    case INSBTC
    case INSETH
    case IOSTBNB
    case IOSTBTC
    case IOSTBUSD
    case IOSTETH
    case IOSTUSDT
    case IOTABNB
    case IOTABTC
    case IOTABUSD
    case IOTAETH
    case IOTAUSDT
    case IOTXBTC
    case IOTXBUSD
    case IOTXETH
    case IOTXUSDT
    case IQBNB
    case IQBUSD
    case IRISBNB
    case IRISBTC
    case IRISBUSD
    case IRISUSDT
    case JSTBNB
    case JSTBTC
    case JSTBUSD
    case JSTUSDT
    case JUVBTC
    case JUVBUSD
    case JUVUSDT
    case KAVABNB
    case KAVABTC
    case KAVABUSD
    case KAVAUSDT
    case KEEPBNB
    case KEEPBTC
    case KEEPBUSD
    case KEEPUSDT
    case KEYBTC
    case KEYETH
    case KEYUSDT
    case KLAYBNB
    case KLAYBTC
    case KLAYBUSD
    case KLAYUSDT
    case KMDBTC
    case KMDBUSD
    case KMDETH
    case KMDUSDT
    case KNCBTC
    case KNCBUSD
    case KNCETH
    case KNCUSDT
    case KP3RBNB
    case KP3RBUSD
    case KSMAUD
    case KSMBNB
    case KSMBTC
    case KSMBUSD
    case KSMUSDT
    case LENDBKRW
    case LENDBTC
    case LENDBUSD
    case LENDETH
    case LENDUSDT
    case LINABTC
    case LINABUSD
    case LINAUSDT
    case LINKAUD
    case LINKBKRW
    case LINKBRL
    case LINKBTC
    case LINKBUSD
    case LINKDOWNUSDT
    case LINKETH
    case LINKEUR
    case LINKGBP
    case LINKNGN
    case LINKPAX
    case LINKTRY
    case LINKTUSD
    case LINKUPUSDT
    case LINKUSDC
    case LINKUSDT
    case LITBTC
    case LITBUSD
    case LITUSDT
    case LOOMBNB
    case LOOMBTC
    case LOOMETH
    case LPTBNB
    case LPTBTC
    case LPTBUSD
    case LPTUSDT
    case LRCBTC
    case LRCBUSD
    case LRCETH
    case LRCUSDT
    case LSKBNB
    case LSKBTC
    case LSKBUSD
    case LSKETH
    case LSKUSDT
    case LTCBNB
    case LTCBRL
    case LTCBTC
    case LTCBUSD
    case LTCDOWNUSDT
    case LTCETH
    case LTCEUR
    case LTCGBP
    case LTCNGN
    case LTCPAX
    case LTCRUB
    case LTCTUSD
    case LTCUAH
    case LTCUPUSDT
    case LTCUSDC
    case LTCUSDT
    case LTOBNB
    case LTOBTC
    case LTOBUSD
    case LTOUSDT
    case LUNABNB
    case LUNABTC
    case LUNABUSD
    case LUNAEUR
    case LUNAUSDT
    case LUNBTC
    case LUNETH
    case MANABTC
    case MANABUSD
    case MANAETH
    case MANAUSDT
    case MASKBNB
    case MASKBUSD
    case MASKUSDT
    case MATICAUD
    case MATICBIDR
    case MATICBNB
    case MATICBRL
    case MATICBTC
    case MATICBUSD
    case MATICEUR
    case MATICGBP
    case MATICRUB
    case MATICTRY
    case MATICUSDT
    case MBLBNB
    case MBLBTC
    case MBLUSDT
    case MBOXBNB
    case MBOXBTC
    case MBOXBUSD
    case MBOXUSDT
    case MCOBNB
    case MCOBTC
    case MCOETH
    case MCOUSDT
    case MDABTC
    case MDAETH
    case MDTBNB
    case MDTBTC
    case MDTUSDT
    case MDXBNB
    case MDXBTC
    case MDXBUSD
    case MDXUSDT
    case MFTBNB
    case MFTBTC
    case MFTETH
    case MFTUSDT
    case MINABNB
    case MINABTC
    case MINABUSD
    case MINAUSDT
    case MIRBTC
    case MIRBUSD
    case MIRUSDT
    case MITHBNB
    case MITHBTC
    case MITHUSDT
    case MKRBNB
    case MKRBTC
    case MKRBUSD
    case MKRUSDT
    case MLNBNB
    case MLNBTC
    case MLNBUSD
    case MLNUSDT
    case MODBTC
    case MODETH
    case MTHBTC
    case MTHETH
    case MTLBTC
    case MTLBUSD
    case MTLETH
    case MTLUSDT
    case NANOBNB
    case NANOBTC
    case NANOBUSD
    case NANOETH
    case NANOUSDT
    case NASBNB
    case NASBTC
    case NASETH
    case NAVBNB
    case NAVBTC
    case NAVETH
    case NBSBTC
    case NBSUSDT
    case NCASHBNB
    case NCASHBTC
    case NCASHETH
    case NEARBNB
    case NEARBTC
    case NEARBUSD
    case NEARUSDT
    case NEBLBNB
    case NEBLBTC
    case NEBLETH
    case NEOBNB
    case NEOBTC
    case NEOBUSD
    case NEOETH
    case NEOPAX
    case NEOTRY
    case NEOTUSD
    case NEOUSDC
    case NEOUSDT
    case NKNBNB
    case NKNBTC
    case NKNUSDT
    case NMRBNB
    case NMRBTC
    case NMRBUSD
    case NMRUSDT
    case NPXSBTC
    case NPXSETH
    case NPXSUSDC
    case NPXSUSDT
    case NUBNB
    case NUBTC
    case NUBUSD
    case NULSBNB
    case NULSBTC
    case NULSETH
    case NULSUSDT
    case NUUSDT
    case NXSBNB
    case NXSBTC
    case NXSETH
    case OAXBTC
    case OAXETH
    case OCEANBNB
    case OCEANBTC
    case OCEANBUSD
    case OCEANUSDT
    case OGBTC
    case OGNBNB
    case OGNBTC
    case OGNBUSD
    case OGNUSDT
    case OGUSDT
    case OMBTC
    case OMBUSD
    case OMGBNB
    case OMGBTC
    case OMGBUSD
    case OMGETH
    case OMGUSDT
    case OMUSDT
    case ONEBIDR
    case ONEBNB
    case ONEBTC
    case ONEBUSD
    case ONEPAX
    case ONETUSD
    case ONEUSDC
    case ONEUSDT
    case ONGBNB
    case ONGBTC
    case ONGUSDT
    case ONTBNB
    case ONTBTC
    case ONTBUSD
    case ONTETH
    case ONTPAX
    case ONTTRY
    case ONTUSDC
    case ONTUSDT
    case ORNBTC
    case ORNBUSD
    case ORNUSDT
    case OSTBNB
    case OSTBTC
    case OSTETH
    case OXTBTC
    case OXTUSDT
    case PAXBNB
    case PAXBTC
    case PAXBUSD
    case PAXETH
    case PAXGBNB
    case PAXGBTC
    case PAXGBUSD
    case PAXGUSDT
    case PAXTUSD
    case PAXUSDT
    case PERLBNB
    case PERLBTC
    case PERLUSDC
    case PERLUSDT
    case PERPBTC
    case PERPBUSD
    case PERPUSDT
    case PHABTC
    case PHABUSD
    case PHAUSDT
    case PHBBNB
    case PHBBTC
    case PHBPAX
    case PHBTUSD
    case PHBUSDC
    case PHXBNB
    case PHXBTC
    case PHXETH
    case PIVXBNB
    case PIVXBTC
    case PIVXETH
    case PNTBTC
    case PNTUSDT
    case POABNB
    case POABTC
    case POAETH
    case POEBTC
    case POEETH
    case POLSBNB
    case POLSBTC
    case POLSBUSD
    case POLSUSDT
    case POLYBNB
    case POLYBTC
    case POLYBUSD
    case POLYUSDT
    case PONDBTC
    case PONDBUSD
    case PONDUSDT
    case POWRBNB
    case POWRBTC
    case POWRETH
    case PPTBTC
    case PPTETH
    case PROMBNB
    case PROMBTC
    case PROMBUSD
    case PROSETH
    case PSGBTC
    case PSGBUSD
    case PSGUSDT
    case PUNDIXETH
    case PUNDIXUSDT
    case QKCBTC
    case QKCETH
    case QLCBNB
    case QLCBTC
    case QLCETH
    case QNTBNB
    case QNTBTC
    case QNTBUSD
    case QNTUSDT
    case QSPBNB
    case QSPBTC
    case QSPETH
    case QTUMBNB
    case QTUMBTC
    case QTUMBUSD
    case QTUMETH
    case QTUMUSDT
    case QUICKBNB
    case QUICKBTC
    case QUICKBUSD
    case QUICKUSDT
    case RADBNB
    case RADBTC
    case RADBUSD
    case RADUSDT
    case RAMPBTC
    case RAMPBUSD
    case RAMPUSDT
    case RAYBNB
    case RAYBUSD
    case RAYUSDT
    case RCNBNB
    case RCNBTC
    case RCNETH
    case RDNBNB
    case RDNBTC
    case RDNETH
    case REEFBTC
    case REEFBUSD
    case REEFUSDT
    case RENBNB
    case RENBTC
    case RENBTCBTC
    case RENBTCETH
    case RENBUSD
    case RENUSDT
    case REPBNB
    case REPBTC
    case REPBUSD
    case REPETH
    case REPUSDT
    case REQBTC
    case REQETH
    case REQUSDT
    case RIFBTC
    case RIFUSDT
    case RLCBNB
    case RLCBTC
    case RLCBUSD
    case RLCETH
    case RLCUSDT
    case ROSEBTC
    case ROSEBUSD
    case ROSEUSDT
    case RPXBNB
    case RPXBTC
    case RPXETH
    case RSRBNB
    case RSRBTC
    case RSRBUSD
    case RSRUSDT
    case RUNEAUD
    case RUNEBNB
    case RUNEBTC
    case RUNEBUSD
    case RUNEEUR
    case RUNEGBP
    case RUNEUSDT
    case RVNBNB
    case RVNBTC
    case RVNBUSD
    case RVNTRY
    case RVNUSDT
    case SALTBTC
    case SALTETH
    case SANDBNB
    case SANDBTC
    case SANDBUSD
    case SANDUSDT
    case SCBNB
    case SCBTC
    case SCBUSD
    case SCETH
    case SCRTBTC
    case SCRTETH
    case SCUSDT
    case SFPBTC
    case SFPBUSD
    case SFPUSDT
    case SHIBAUD
    case SHIBBRL
    case SHIBBUSD
    case SHIBEUR
    case SHIBRUB
    case SHIBTRY
    case SHIBUSDT
    case SKLBTC
    case SKLBUSD
    case SKLUSDT
    case SKYBNB
    case SKYBTC
    case SKYETH
    case SLPBUSD
    case SLPETH
    case SLPUSDT
    case SNGLSBTC
    case SNGLSETH
    case SNMBTC
    case SNMETH
    case SNTBTC
    case SNTETH
    case SNXBNB
    case SNXBTC
    case SNXBUSD
    case SNXUSDT
    case SOLAUD
    case SOLBIDR
    case SOLBNB
    case SOLBRL
    case SOLBTC
    case SOLBUSD
    case SOLEUR
    case SOLGBP
    case SOLRUB
    case SOLTRY
    case SOLUSDC
    case SOLUSDT
    case SPARTABNB
    case SRMBIDR
    case SRMBNB
    case SRMBTC
    case SRMBUSD
    case SRMUSDT
    case STEEMBNB
    case STEEMBTC
    case STEEMETH
    case STMXBNB
    case STMXBTC
    case STMXBUSD
    case STMXETH
    case STMXUSDT
    case STORJBTC
    case STORJBUSD
    case STORJETH
    case STORJUSDT
    case STORMBNB
    case STORMBTC
    case STORMETH
    case STORMUSDT
    case STPTBNB
    case STPTBTC
    case STPTBUSD
    case STPTUSDT
    case STRATBNB
    case STRATBTC
    case STRATBUSD
    case STRATETH
    case STRATUSDT
    case STRAXBTC
    case STRAXBUSD
    case STRAXETH
    case STRAXUSDT
    case STXBNB
    case STXBTC
    case STXBUSD
    case STXUSDT
    case SUBBTC
    case SUBETH
    case SUNBTC
    case SUNBUSD
    case SUNUSDT
    case SUPERBTC
    case SUPERBUSD
    case SUPERUSDT
    case SUSDBTC
    case SUSDETH
    case SUSDUSDT
    case SUSHIBIDR
    case SUSHIBNB
    case SUSHIBTC
    case SUSHIBUSD
    case SUSHIDOWNUSDT
    case SUSHIUPUSDT
    case SUSHIUSDT
    case SWRVBNB
    case SWRVBUSD
    case SXPAUD
    case SXPBIDR
    case SXPBNB
    case SXPBTC
    case SXPBUSD
    case SXPDOWNUSDT
    case SXPEUR
    case SXPGBP
    case SXPTRY
    case SXPUPUSDT
    case SXPUSDT
    case SYSBNB
    case SYSBTC
    case SYSBUSD
    case SYSETH
    case SYSUSDT
    case TCTBNB
    case TCTBTC
    case TCTUSDT
    case TFUELBNB
    case TFUELBTC
    case TFUELPAX
    case TFUELTUSD
    case TFUELUSDC
    case TFUELUSDT
    case THETABNB
    case THETABTC
    case THETABUSD
    case THETAETH
    case THETAEUR
    case THETAUSDT
    case TKOBIDR
    case TKOBTC
    case TKOBUSD
    case TKOUSDT
    case TLMBTC
    case TLMBUSD
    case TLMTRY
    case TLMUSDT
    case TNBBTC
    case TNBETH
    case TNTBTC
    case TNTETH
    case TOMOBNB
    case TOMOBTC
    case TOMOBUSD
    case TOMOUSDC
    case TOMOUSDT
    case TORNBNB
    case TORNBTC
    case TORNBUSD
    case TORNUSDT
    case TRBBNB
    case TRBBTC
    case TRBBUSD
    case TRBUSDT
    case TRIBEBNB
    case TRIBEBTC
    case TRIBEBUSD
    case TRIBEUSDT
    case TRIGBNB
    case TRIGBTC
    case TRIGETH
    case TROYBNB
    case TROYBTC
    case TROYUSDT
    case TRUBTC
    case TRUBUSD
    case TRURUB
    case TRUUSDT
    case TRXAUD
    case TRXBNB
    case TRXBTC
    case TRXBUSD
    case TRXDOWNUSDT
    case TRXETH
    case TRXEUR
    case TRXNGN
    case TRXPAX
    case TRXTRY
    case TRXTUSD
    case TRXUPUSDT
    case TRXUSDC
    case TRXUSDT
    case TRXXRP
    case TUSDBNB
    case TUSDBTC
    case TUSDBTUSD
    case TUSDBUSD
    case TUSDETH
    case TUSDUSDT
    case TVKBTC
    case TVKBUSD
    case TVKUSDT
    case TWTBTC
    case TWTBUSD
    case TWTUSDT
    case UFTBUSD
    case UFTETH
    case UMABTC
    case UMAUSDT
    case UNFIBNB
    case UNFIBTC
    case UNFIBUSD
    case UNFIUSDT
    case UNIAUD
    case UNIBNB
    case UNIBTC
    case UNIBUSD
    case UNIDOWNUSDT
    case UNIEUR
    case UNIUPUSDT
    case UNIUSDT
    case USDCBNB
    case USDCBUSD
    case USDCPAX
    case USDCTUSD
    case USDCUSDT
    case USDPBUSD
    case USDPUSDT
    case USDSBUSDS
    case USDSBUSDT
    case USDSPAX
    case USDSTUSD
    case USDSUSDC
    case USDSUSDT
    case USDTBIDR
    case USDTBKRW
    case USDTBRL
    case USDTBVND
    case USDTDAI
    case USDTGYEN
    case USDTIDRT
    case USDTNGN
    case USDTRUB
    case USDTTRY
    case USDTUAH
    case USDTZAR
    case UTKBTC
    case UTKBUSD
    case UTKUSDT
    case VENBNB
    case VENBTC
    case VENETH
    case VENUSDT
    case VETBNB
    case VETBTC
    case VETBUSD
    case VETETH
    case VETEUR
    case VETGBP
    case VETTRY
    case VETUSDT
    case VGXBTC
    case VGXETH
    case VIABNB
    case VIABTC
    case VIAETH
    case VIBBTC
    case VIBEBTC
    case VIBEETH
    case VIBETH
    case VIDTBTC
    case VIDTBUSD
    case VIDTUSDT
    case VITEBNB
    case VITEBTC
    case VITEUSDT
    case VTHOBNB
    case VTHOBUSD
    case VTHOUSDT
    case WABIBNB
    case WABIBTC
    case WABIETH
    case WANBNB
    case WANBTC
    case WANETH
    case WANUSDT
    case WAVESBNB
    case WAVESBTC
    case WAVESBUSD
    case WAVESETH
    case WAVESPAX
    case WAVESRUB
    case WAVESTUSD
    case WAVESUSDC
    case WAVESUSDT
    case WAXPBNB
    case WAXPBTC
    case WAXPBUSD
    case WAXPUSDT
    case WBTCBTC
    case WBTCETH
    case WINBNB
    case WINBRL
    case WINBTC
    case WINBUSD
    case WINEUR
    case WINGBNB
    case WINGBTC
    case WINGBUSD
    case WINGSBTC
    case WINGSETH
    case WINGUSDT
    case WINTRX
    case WINUSDC
    case WINUSDT
    case WNXMBNB
    case WNXMBTC
    case WNXMBUSD
    case WNXMUSDT
    case WPRBTC
    case WPRETH
    case WRXBNB
    case WRXBTC
    case WRXBUSD
    case WRXEUR
    case WRXUSDT
    case WTCBNB
    case WTCBTC
    case WTCETH
    case WTCUSDT
    case XECBUSD
    case XECUSDT
    case XEMBNB
    case XEMBTC
    case XEMBUSD
    case XEMETH
    case XEMUSDT
    case XLMBNB
    case XLMBTC
    case XLMBUSD
    case XLMDOWNUSDT
    case XLMETH
    case XLMEUR
    case XLMPAX
    case XLMTRY
    case XLMTUSD
    case XLMUPUSDT
    case XLMUSDC
    case XLMUSDT
    case XMRBNB
    case XMRBTC
    case XMRBUSD
    case XMRETH
    case XMRUSDT
    case XRPAUD
    case XRPBEARBUSD
    case XRPBEARUSDT
    case XRPBIDR
    case XRPBKRW
    case XRPBNB
    case XRPBRL
    case XRPBTC
    case XRPBULLBUSD
    case XRPBULLUSDT
    case XRPBUSD
    case XRPDOWNUSDT
    case XRPETH
    case XRPEUR
    case XRPGBP
    case XRPNGN
    case XRPPAX
    case XRPRUB
    case XRPTRY
    case XRPTUSD
    case XRPUPUSDT
    case XRPUSDC
    case XRPUSDT
    case XTZBNB
    case XTZBTC
    case XTZBUSD
    case XTZDOWNUSDT
    case XTZUPUSDT
    case XTZUSDT
    case XVGBTC
    case XVGBUSD
    case XVGETH
    case XVGUSDT
    case XVSBNB
    case XVSBTC
    case XVSBUSD
    case XVSUSDT
    case XZCBNB
    case XZCBTC
    case XZCETH
    case XZCUSDT
    case XZCXRP
    case YFIBNB
    case YFIBTC
    case YFIBUSD
    case YFIDOWNUSDT
    case YFIEUR
    case YFIIBNB
    case YFIIBTC
    case YFIIBUSD
    case YFIIUSDT
    case YFIUPUSDT
    case YFIUSDT
    case YGGBNB
    case YGGBTC
    case YGGBUSD
    case YGGUSDT
    case YOYOBNB
    case YOYOBTC
    case YOYOETH
    case ZECBNB
    case ZECBTC
    case ZECBUSD
    case ZECETH
    case ZECPAX
    case ZECTUSD
    case ZECUSDC
    case ZECUSDT
    case ZENBNB
    case ZENBTC
    case ZENBUSD
    case ZENETH
    case ZENUSDT
    case ZILBIDR
    case ZILBNB
    case ZILBTC
    case ZILBUSD
    case ZILETH
    case ZILUSDT
    case ZRXBNB
    case ZRXBTC
    case ZRXBUSD
    case ZRXETH
    case ZRXUSDT
}
